# Generated by Django 4.1.4 on 2023-07-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('capture_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
